#!/bin/bash
#ng generate component produto/produto-list
#ng generate service produto/produto

#npm i @ng-bootstrap/ng-bootstrap --save

#npm i bootstrap --save

# Gerar serviço para a categoria
#ng g s categoria/categoria

# Gerar componente de listagem para a categoria
#ng g c categoria/categoria-list

#Gerar componente de formulário para o produto
ng g c produto/produto-form